<MyLayout>

	BoxLayout
		orientation: "vertical"
		size: root.width, root.height

		spacing: 20
		padding: 50

		## button height 10%
		Button:
			text: "Hello World"
			size_hint:(1, 0.1)

		## button fixed width
		Button:
			text: "Goodbye World"
			size_hint:(None, None)
			width: 100
			height: 50

		## center button and half size
		Button:
			text: "I'm hungry"
			size_hint:(1, 1)
			pos_hint: {'center_x': 0.5}